# Generated by Django 5.1.1 on 2024-10-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_address_profile_contact_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
